# Generated by Django 3.1.4 on 2020-12-30 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('linter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='statuscode',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='status_code', to='linter.statuscode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(unique=True, verbose_name=uuid.UUID('5cca70ad-ca1b-485e-9350-1581c0907e1e')),
        ),
    ]
