# Generated by Django 3.1.4 on 2020-12-30 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('linter', '0002_auto_20201230_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(unique=True, verbose_name=uuid.UUID('e12f20cf-a0f6-48cb-aac8-6760b372274b')),
        ),
    ]
