# Generated by Django 3.1.4 on 2021-01-02 23:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('linter', '0003_auto_20201230_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6f4b7f3b-a851-4665-badf-d1d6ce0e9411'), unique=True),
        ),
    ]
