# Generated by Django 3.1.4 on 2021-01-03 01:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('linter', '0004_auto_20210103_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='session',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 6, 11, 0, 175158)),
        ),
        migrations.AlterField(
            model_name='code',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7fdb3a7a-79b9-460f-885c-9ccc39c833f5'), unique=True),
        ),
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='TEST', max_length=250)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linter.document')),
            ],
        ),
    ]
